version: '3.7'

services: 
  nginx: 
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ~/data:/usr/share/nginx/data
    ports:
      - 8080:80
      - 443:443

  local-social-ui:
    image: local-social-ui:dev
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    stdin_open: true
    # volumes:
    #   - '.:/app'
    #   - '/app/node_modules'
    ports: 
      - 3001:3000
    # environment: 
    #   - CHOKIDAR_USEPOLLING=true